services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.django-app-api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
       sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    volumes:
      - dev_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
#    command: >
#      sh -c 'su - postgres -c "/usr/local/bin/pg_ctl reload -D /var/lib/postgresql/data"'
#      sh -c "sed -i 's|127.0.0.1/32|172.16.0.0/12|' /var/lib/postgresql/data/pg_hba.conf"
#      sh -c "su - postgres pg_ctl reload  -D /var/lib/postgresql/data"
#    command: >
#      sh -c "\cp /postres/pg_hba.:w conf /var/lib/postgresql/data/pg_hba.conf"
volumes:
  dev_db_data:
