---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test Code with Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Huba
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test Unit
        run: |
          docker compose run --rm app sh -c "python manage.py test"

      - name: Lint Code Base
        run: |
          docker compose run --rm app sh -c "flake8"